language: php

php:  5.6

cache: bundler

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source
  - php artisan doctrine:schema:create
  - php artisan db:seed


script:
  - phpunit