language: php

php:  5.6

cache: bundler

services:
  - mysql


install:
  - composer require satooshi/php-coveralls

before_script:
  - mkdir -p build/logs
  - composer self-update
  - composer install --no-interaction --prefer-source
  - cp .travis.env .env
  - mysql -e 'create database np;'
  - php artisan doctrine:schema:create
  - php artisan db:seed


script:
  - phpunit --coverage-clover build/logs/clover.xml

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
