<?php

namespace DoctrineProxies\__CG__\App\Domain\Model\Evaluation;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class IAC extends \App\Domain\Model\Evaluation\IAC implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'student', 'branch', 'iacGoals', 'dateRange'];
        }

        return ['__isInitialized__', 'id', 'student', 'branch', 'iacGoals', 'dateRange'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (IAC $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getStudent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStudent', []);

        return parent::getStudent();
    }

    /**
     * {@inheritDoc}
     */
    public function addGoal(\App\Domain\Model\Education\Goal $goal, $date = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addGoal', [$goal, $date]);

        return parent::addGoal($goal, $date);
    }

    /**
     * {@inheritDoc}
     */
    public function allIACGoals()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'allIACGoals', []);

        return parent::allIACGoals();
    }

    /**
     * {@inheritDoc}
     */
    public function removeIACGoal(\App\Domain\Model\Evaluation\IACGoal $item)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIACGoal', [$item]);

        return parent::removeIACGoal($item);
    }

    /**
     * {@inheritDoc}
     */
    public function setDateRange($dateRange)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateRange', [$dateRange]);

        return parent::setDateRange($dateRange);
    }

    /**
     * {@inheritDoc}
     */
    public function isActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isActive', []);

        return parent::isActive();
    }

    /**
     * {@inheritDoc}
     */
    public function isActiveSince()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isActiveSince', []);

        return parent::isActiveSince();
    }

    /**
     * {@inheritDoc}
     */
    public function isActiveUntil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isActiveUntil', []);

        return parent::isActiveUntil();
    }

    /**
     * {@inheritDoc}
     */
    public function wasActiveAt(\DateTime $date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'wasActiveAt', [$date]);

        return parent::wasActiveAt($date);
    }

    /**
     * {@inheritDoc}
     */
    public function wasActiveBetween(\App\Domain\Model\Time\DateRange $dateRange)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'wasActiveBetween', [$dateRange]);

        return parent::wasActiveBetween($dateRange);
    }

    /**
     * {@inheritDoc}
     */
    public function resetStart($start)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'resetStart', [$start]);

        return parent::resetStart($start);
    }

    /**
     * {@inheritDoc}
     */
    public function block($end = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'block', [$end]);

        return parent::block($end);
    }

}
